### PR TITLE
added Snorlax

### PR DESCRIPTION
**Pull request by Alve2000**
I have added a new pokemon character,  "Snorlax"

### CODE REVIEW

**Comment by Knackie** [comment]
No type defined..

**Comment by Alve2000** [comment]
Hy Knackie, I have defined the type.
Kindly review, merge and put the hacktoberfest label.
Thanks !

**Comment by Knackie** [comment]
image snorlax is a normal type.

**Comment by Alve2000** [comment]
> image snorlax is a normal type.

Changed type to normal

**Comment by Alve2000** [comment]
updated snorlax.java

**Comment by Knackie** [comment]
Thanks !

**Pull request merged**
